const data = {
  products: [
    {
      id: "1",
      name: "Fly Shoes",
      category: "Shoes",
      image: "/images/product-1.jpg",
      price: 120,
      countInStock: 10,
      brand: "Gucci",
      rating: 0.5,
      numReviews: 23,
      description: "high quality products",
    },
    {
      id: "2",
      name: "High Top Shoes",
      category: "Shoes",
      image: "/images/product-2.jpg",
      price: 20,
      countInStock: 2,
      brand: "Prada",
      rating: 4.5,
      numReviews: 54,
      description: "high quality product",
    },
    {
      id: "3",
      name: "Low Top Shoes",
      category: "Shoes",
      image: "/images/product-6.jpg",
      price: 50,
      countInStock: 0,
      brand: "Chanel",
      rating: 3.5,
      numReviews: 90,
      description: "high quality product",
    },
    {
      id: "4",
      name: "Different Typa Shoe",
      category: "Shoes",
      image: "/images/product-4.jpg",
      price: 45,
      countInStock: 5,
      brand: "Versaci",
      rating: 2.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      id: "5",
      name: "Fly Ass Shoes",
      category: "Shoes",
      image: "/images/product-5.jpg",
      price: 89,
      countInStock: 20,
      brand: "Timbs",
      rating: 1.5,
      numReviews: 25,
      description: "high quality product",
    },
    {
      id: "6",
      name: "Good Shoes",
      category: "Shoes",
      image: "/images/product-6.jpg",
      price: 423,
      countInStock: 1,
      brand: "Nike",
      rating: 5,
      numReviews: 12,
      description: "high quality product",
    },
  ],
};
export default data;
