const data = {
  products: [
    {
      id: "1",
      name: "Fly Shoes",
      category: "Shoes",
      image: "/images/product-1.jpg",
      price: 120,
      brand: "Gucci",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      id: "2",
      name: "High Top Shoes",
      category: "Shoes",
      image: "/images/product-2.jpg",
      price: 120,
      brand: "Prada",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      id: "3",
      name: "Low Top Shoes",
      category: "Shoes",
      image: "/images/product-6.jpg",
      price: 120,
      brand: "Chanel",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      id: "4",
      name: "Different Typa Shoe",
      category: "Shoes",
      image: "/images/product-4.jpg",
      price: 120,
      brand: "Versaci",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      id: "5",
      name: "Fly Ass Shoes",
      category: "Shoes",
      image: "/images/product-5.jpg",
      price: 120,
      brand: "Timbs",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      id: "6",
      name: "Good Shoes",
      category: "Shoes",
      image: "/images/product-6.jpg",
      price: 120,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
  ],
};
export default data;
